Repository Beauty-inside/stocking-backend, pull requests merged in 2021-06, with the labels that each got.

#20 Auth 모듈 개발, 각종 설정
  Dockerfile
  build.gradle
  src/main/java/bis/stock/back/domain/auth/AuthController.java
  src/main/java/bis/stock/back/domain/auth/AuthService.java
  src/main/java/bis/stock/back/domain/auth/dto/AccessTokenDto.java
  src/main/java/bis/stock/back/domain/auth/dto/JoinDto.java
  src/main/java/bis/stock/back/domain/auth/dto/LoginDto.java
  src/main/java/bis/stock/back/domain/user/User.java
  src/main/java/bis/stock/back/domain/user/UserRepository.java
  src/main/java/bis/stock/back/domain/user/UserRole.java
  src/main/java/bis/stock/back/global/config/security/CustomUserDetailService.java
  src/main/java/bis/stock/back/global/config/security/JwtAuthenticationFilter.java
  src/main/java/bis/stock/back/global/config/security/JwtTokenProvider.java
  src/main/java/bis/stock/back/global/config/security/WebSecurityConfig.java
  src/main/java/bis/stock/back/global/exception/ForbiddenException.java
  src/main/java/bis/stock/back/global/exception/NotFoundException.java
  src/main/java/bis/stock/back/global/util/CookieUtil.java
  src/main/java/bis/stock/back/global/util/RedisUtil.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/test/java/bis/stock/back/global/util/CookieUtilTest.java
  src/test/java/bis/stock/back/global/util/RedisUtilTest.java
Labels: enhancement

#22 Structuring Stock and Asset parts
  src/main/java/bis/stock/back/domain/asset/AssetController.java
  src/main/java/bis/stock/back/domain/asset/AssetService.java
  src/main/java/bis/stock/back/domain/asset/dto/AssetDto.java
  src/main/java/bis/stock/back/domain/asset/dto/ExpenditureDto.java
  src/main/java/bis/stock/back/domain/asset/dto/IncomeDto.java
  src/main/java/bis/stock/back/domain/stock/StockController.java
  src/main/java/bis/stock/back/domain/stock/StockService.java
  src/main/java/bis/stock/back/domain/stock/dto/StockDto.java
Labels: structuring

#24 ReadME 파일 업데이트
  README.md
Labels: documentation
